# Generated by Django 3.2.19 on 2023-06-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, null=True, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, null=True, verbose_name='CPF')),
                ('endereco', models.CharField(max_length=60, null=True, verbose_name='Endereço')),
                ('valor', models.FloatField(null=True, verbose_name='Valor Emprestimo')),
                ('status', models.CharField(blank=True, max_length=10, null=True, verbose_name='Status')),
            ],
        ),
    ]
